### ISSUE TITLE
ttn app:  NoappId, accessKey or discovery address

### ISSUE THREAD

**Issue by dicktonyboy** [TheThingsNetwork/nodered-app-node#50] opened 2018-11-03 23:48 UTC
Brand new Stretch Pi install on Pi 3, then run the install script  bash <(curl -sL https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered)   Node v11.1.0  npm V 6.4.1  So far so good.    The ttn- install using the GUI install fails or on the second attempt loads the three node BUT when trying to configure Node Properties there is no edit/add option in the App option box.  Using the text install option in ~/.node-red and the installation completes providing the add/edit (little pen icon) option.  The who thing appears to function correctly (using the gui) BUT the log complains that no appId, accessKey or discovery address has been recorded.. Nothing therefore functions. Any ideas folks?

**Comment by johanstokking** [comment] 2018-11-04 01:14
Thanks for reporting, we'll look into this.

**Comment by Octoate** [comment] 2018-11-11 22:01
Hi,
I have the same problem, however I am using Docker on my Raspberry Pi and the official Docker image for it ([Node-Red Docker Image](https://hub.docker.com/r/nodered/node-red-docker/). I tried to install the TTN nodes via GUI, command line and the node-red remote administration tool, but always with the same result: the ttn-app node is not working.
On my desktop system I am using the same setup - but on a x86 machine and the TTN nodes were installed and working as expected.

As you can see in the screenshot below, the "ttn-app" is disabled and there is a warning sign with an JavaScript object (not much to see here...):
![ttn-app-notworking](https://user-images.githubusercontent.com/1457566/48318731-ede0f200-e604-11e8-8fcc-5c21104ab1fc.png)

**Comment by johanstokking** [comment] 2018-11-12 11:43
That looks like an older version of the TTN nodes for Node-RED; `ttn app` is gone now.

**Comment by Octoate** [comment] 2018-11-13 19:44
Strange. It tells me that I am using the latest version: v2.0.4.

**Comment by johanstokking** [comment] 2018-11-14 09:38
@Octoate the `ttn app` is a configuration node, hence it's grayed out. So contrary to what I said above, it is still being used, but not supposed to be placed on your flows as a node.

@dicktonyboy I cannot reproduce this. This sounds like an installation issue, by a mixup of GUI and CLI installs. I need a clean set of steps to reproduce from a known state, instead of a list of things that have been tried with a certain result.

**Comment by dicktonyboy** [comment] 2018-11-14 23:47
Wenner World of Weirdness continues.  Made a clean Stretch install and applied the update script from the Node Red site. Installed ttn and had the same error - ie no blue 'connected' circle.  Moved the Pi to another network (forcing static IP - no other change) and the blue connected indicators appear!!!  (Aside- using older firefox 24.5.0).  Reverted back to original physical network (and dhcp) and connected lights do not appear.  Thought it may be the Ad-blocker so used IE Tor Edge Firefox Opera and Chrome but no - all browsers act consistently. Baffled - but can't move back to 2nd network due to access issues for the next week.

**Comment by johanstokking** [comment] 2018-11-15 11:18
That's weird. Please also keep a close look at the browser's JavaScript/console output.

**Comment by RvRijsselt** [comment] 2018-11-25 22:39
I probably had the same initial issue: 
 - there is no edit/add option in the App option box
 - [object Object] error in the manage palette dialog
 - and the following log at startup (same as @Octoate)
> nov 25 21:45:05 mark1 Node-RED[8669]: 25 Nov 21:45:05 - [warn] [node-red-contrib-ttn/ttn-app] Error: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: 
> version `GLIBCXX_3.4.21' not found (required by /home/pi/.node-red/node_modules/grpc/src/node/extension_binary/node-v47-linux-arm-glibc/grpc_node.
> node)

I was able to fix my installation by running the following in the .node-red path:
`npm rebuild --build-from-source=grpc`

Note however that I am running Raspbian GNU/Linux 8 (jessie). Oh and the network issues indeed sound very weird and probably not related to this. Do you have any startup warnings or errors from node-red? You can also increase the log level of node-red.

**Comment by johanstokking** [comment] 2018-11-26 16:30
@RvRijsselt great, that sounds as a sensible solution indeed. Could you make a PR for the README?

**Comment by johanstokking** [comment] 2018-11-27 09:11
Closed by #53

**Closed by johanstokking** 2018-11-27 09:11 UTC
Labels: bug

**Comment by Octoate** [comment] 2018-12-02 22:39
> I was able to fix my installation by running the following in the .node-red path:
> `npm rebuild --build-from-source=grpc`
Finally, that fixed the issue. Thanks a lot. Everything is working now!
