### ISSUE TITLE
Node-red-contrib-ttn installation error in node-red 0.18.4 ( Win10 )

### ISSUE THREAD

**Issue by Batigolle** [TheThingsNetwork/nodered-app-node#43] opened 2018-03-02 09:40 UTC
Initial situation, working ok:     Windows10 + node-red 0.18.2 + node-red-contrib-ttn

After updating to version 0.18.4, manage palette, reports that contib-ttn needs to be reinstalled.

Tried to do the installation from manage palette, without success.
Tried to reinstall the command line node (npm install node-red-contrib-ttn), 
but I get many error reports, reinstallation is not successful.

Attached installation errors log
[2018-03-01T21_39_35_174Z-debug.log](https://github.com/TheThingsNetwork/nodered-app-node/files/1774480/2018-03-01T21_39_35_174Z-debug.log)

node-red environment versions
1 Mar 22:42:46 - [info] Node-RED version: v0.18.4
1 Mar 22:42:46 - [info] Node.js  version: v8.9.4
1 Mar 22:42:46 - [info] Windows_NT 10.0.16299 x64 LE
1 Mar 22:42:47 - [info] Loading palette nodes
1 Mar 22:42:50 - [info] Dashboard version 2.8.2 started at /ui
.........

Note: 
In the raspbian environment, raspberry PI3, updated to version 0.18.4 with node node-red-contrib-ttn, 
works correctly

Thanks

**Comment by johncaipa** [comment] 2018-03-02 21:55
i cant install it in Node-RED instance on IBM Cloud now

**Comment by johanstokking** [comment] 2018-03-04 15:53
@Batigolle what is your npm and node version?

I cannot reproduce on High Sierra, npm 5.4.0, node 9.5.0, node-red 0.18.4 and node-red-contrib-ttn 2.0.4.

@johncaipa @Batigolle does a previous version work, i.e. `2.0.1`? That should be `npm install node-red-contrib-ttn@2.0.1`

**Comment by johncaipa** [comment] 2018-03-04 16:41
@johanstokking in my case it seems to be a problem in the new version of node-RED(v0.18.4), I had to do downgrate to both node-RER (v0.17.5) and node-red-contrib-ttn (v2.0.1) this since it does not allow to install it from the graphical interface anymore, I have to add it to the package.json

**Comment by johanstokking** [comment] 2018-03-04 17:30
That may have something to do with the requirement to run a script to install the grpc dependency.

**Comment by Batigolle** [comment] 2018-03-04 20:03
@johanstokking  my current version are :
npm 5.6.0
node.js 8.9.4
node-red 0.18.4

I have tried to install the contrib-ttn 2.0.1 version, as you suggested
this is the output of the command
![image](https://user-images.githubusercontent.com/19666466/36949945-223d72ee-1fef-11e8-8693-40f7c775af54.png)

After starting node-red, I see the ttn nodes in the left bar and
 in Manage palette it is suggested to update the module to 2.0.4

**Comment by johanstokking** [comment] 2018-03-05 11:08
@Batigolle You should be working from the `.node-red` directory. Please see general instructions for installing Node-RED nodes.

**Comment by Batigolle** [comment] 2018-03-05 18:46
@johanstokking you're right, 
I repeated the installation
![image](https://user-images.githubusercontent.com/19666466/36993321-d153952e-20ad-11e8-80c4-2c8f06064b3b.png)

**Comment by johanstokking** [comment] 2018-03-05 21:47
@Batigolle this looks good. How about `2.0.4`?

**Comment by Batigolle** [comment] 2018-03-05 22:01
@johanstokking  
I repeated the installation 2.0.4, this it's output
![image](https://user-images.githubusercontent.com/19666466/37002034-ae398d1c-20c8-11e8-8831-5cea46a84c84.png)

after start node-red , on manage palette , it still requires updating to the version 2.0.4
![image](https://user-images.githubusercontent.com/19666466/37002198-2cce0248-20c9-11e8-95cd-a554583eefab.png)

**Comment by johanstokking** [comment] 2018-03-06 09:06
I cannot reproduce still. Can you verify that you don't have `node-red-contrib-ttn@2.0.1` installed globally?

<img width="578" alt="screen shot 2018-03-06 at 10 06 19" src="https://user-images.githubusercontent.com/13334001/37023396-17d64faa-2126-11e8-9bf0-fc1cd3bb8ac1.png">

**Comment by Batigolle** [comment] 2018-03-06 16:56
@johanstokking  both from Manage palette and from User Setting, the result is always the same
![image](https://user-images.githubusercontent.com/19666466/37046018-9bc4aaf0-2167-11e8-9b56-ce289680ba55.png)

**Comment by Batigolle** [comment] 2018-03-06 17:02
@johanstokking  if I try to select, from Manage Palette "Update to 2.0.4", obtaining the following error
![image](https://user-images.githubusercontent.com/19666466/37046365-7b12cd22-2168-11e8-85d0-6f3b5b5c5baf.png)

**Comment by johanstokking** [comment] 2018-03-06 20:46
That indeed suggests that the module is installed globally, not locally. 

1. See https://docs.npmjs.com/getting-started/uninstalling-global-packages
2. See https://docs.npmjs.com/getting-started/installing-npm-packages-locally (in `$HOME/.node-red`)

**Comment by Batigolle** [comment] 2018-03-07 17:20
Hi @johanstokking  , I tried to uninstall the node with your instructions 1), but nothing happened.

I investigated the global and local settings of the installations and I found a lot of confusion in the folders on the computer, I found 4 folders ".../node_modules "  !  

I think it's due to a wrong update of nod-red to the vers. 0.18.4

I deleted only one node_modules directory of the four and the subsequent installation of node-red-contrib-ttn 2.0.4 ,was successfully terminated

Currently the situation of the node_modules folders is as follows:
1) C:\Users\lucky\AppData\Roaming\npm\node_modules
![image](https://user-images.githubusercontent.com/19666466/37106721-d7135c02-2232-11e8-85c7-1a18d6772f97.png)
2) C:\Users\lucky\AppData\Roaming\npm\node_modules\node-red\node_modules
3) C:\Users\lucky\.node-red\node_modules

the 1) should be that of the installations of the global nodes
the 3) correct of the installationa of the local nodes
the 2) does not convince me, it seems strange that there is a folder node_modules nested in another folder node_modules

However, for now, node-red seems to work

To clean up the environment, I could try to uninstall node-red and reinstall it, but I can not find instructions on how to uninstall it

Thanks a lot for your support

**Comment by johanstokking** [comment] 2018-03-09 15:02
@Batigolle thanks for the details. Indeed, Node.js and Node-RED installations are very easy to become a complete mess, certainly under Windows. This doesn't seem related to this particular repository so I'm closing this issue.

**Closed by johanstokking** 2018-03-09 15:02 UTC
Labels: bug
